### ISSUE TITLE
Change the names of component files

### ISSUE THREAD

**Issue by amit-ksh** [koders-in/Portfolio#25]
- change the App component file name to index.jsx
Example:-  About.jsx ---> index.jsx
This allows us to import the component using only 
`import About from './About';` 
instead like this
`import About from './About'/About;`

- change the App component CSS file name to style.css
Example:- About.css to style.css

**Comment by valasubramanian-tw** [comment]
@amit-ksh I would like to work on this issue. Can you assign it to me?

**Comment by 1stdevfriend** [comment]
@valasubramanian-tw There you go :)

**Comment by amit-ksh** [comment]
@valasubramanian-tw I'm not authorized to assign the issue to someone.

**Comment by valasubramanian-tw** [comment]
@1stdevfriend Can you assign this issue to me?

**Comment by 1stdevfriend** [comment]
Done :)

**Comment by valasubramanian-tw** [comment]
@1stdevfriend this issue is not resolved yet. Can you reopen this issue? I will create a PR for this issue.

**Comment by 1stdevfriend** [comment]
Yes. For sure.
